baseURL: https://www.vinhomeu.com/
languageCode: en
title: Vinhomeu

defaultContentLanguage: en
languages:
  en:
    menu:
      main:
      - identifier: about
        name: About
        url: /about/
        weight: -110
      - identifier: varities
        name: Varieties
        url: /varieties/
        weight: -120
    title: Vinhomeu
    weight: 1

  de:
    menu:
      main:
      - identifier: about
        name: Über
        url: /de/about/
        weight: -110
      - identifier: varities
        name: Weinsorten
        url: /de/varieties/
        weight: -120
    title: Vinhomeu
    weight: 2