baseURL: https://www.vinhomeu.com/
languageCode: en-us
title: Vinhomeu
sectionPagesMenu: main




defaultContentLanguage: en
languages:
  en:
    menu:
      main:
      - identifier: about
        name: About
        url: /about/
        weight: -110
    title: Vinhomeu
    weight: 1
  de:
    menu:
      main:
      - identifier: about
        name: Über
        url: /de/about/
        weight: -110
    title: Vinhomeu
    weight: 2